[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:xvfb]
command=/usr/bin/Xvfb %(ENV_DISPLAY)s -screen 0 %(ENV_WIDTH)sx%(ENV_HEIGHT)sx%(ENV_DEPTH)s -ac +extension GLX +render -noreset
autostart=true
autorestart=true
priority=10
user=glasswing
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:plasma]
command=/bin/bash -lc 'until xdpyinfo -display "$DISPLAY" >/dev/null 2>&1; do sleep 1; done; exec dbus-run-session -- startplasma-x11'
autostart=true
autorestart=true
priority=20
user=glasswing
environment=DISPLAY="%(ENV_DISPLAY)s",HOME="/home/glasswing",USER="glasswing",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s",KDE_FULL_SESSION="true",KDE_SESSION_VERSION="5",QT_X11_NO_MITSHM="1",PLASMA_USE_QT_SCALING="1",QT_SCALE_FACTOR="1.25",GDK_SCALE="1",GDK_DPI_SCALE="1.25"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:x11vnc]
command=/bin/bash -lc 'until xdpyinfo -display "$DISPLAY" >/dev/null 2>&1; do sleep 1; done; exec x11vnc -display "$DISPLAY" -rfbport 5900 -rfbauth /home/glasswing/.vnc/passwd -forever -shared -noxdamage -repeat -xkb -quiet'
autostart=true
autorestart=true
priority=30
user=glasswing
environment=DISPLAY="%(ENV_DISPLAY)s",HOME="/home/glasswing",USER="glasswing",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:novnc]
command=/usr/bin/websockify --web=/opt/glasswing/www 0.0.0.0:8080 localhost:5900
autostart=true
autorestart=true
priority=40
user=glasswing
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


[program:xrdp-sesman]
command=/usr/sbin/xrdp-sesman --nodaemon
autostart=true
autorestart=true
priority=35
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:xrdp]
command=/usr/sbin/xrdp --nodaemon
autostart=true
autorestart=true
priority=36
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
